# Generated by Django 3.1.2 on 2020-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpllist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, verbose_name='CUSTOMER')),
            ],
        ),
        migrations.CreateModel(
            name='DetectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detect_name', models.CharField(max_length=30, verbose_name='DETECT_NAME')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='CUSTOMER_ID')),
                ('permission_lvl', models.IntegerField(verbose_name='PERMISSION_LVL')),
                ('user_id', models.CharField(max_length=30, verbose_name='USER_ID')),
                ('user_pw', models.CharField(max_length=30, verbose_name='USER_PW')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(verbose_name='CUSTOMER_ID')),
                ('template_path', models.CharField(max_length=100, verbose_name='TEMPLATE_PATH')),
                ('detect_module', models.IntegerField(verbose_name='DETECT_MODULE')),
                ('permission_id', models.IntegerField(verbose_name='PERMISSION_ID')),
                ('url_path', models.CharField(max_length=200, verbose_name='DETECT_MODULE')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='TITLE'),
        ),
    ]
