# Generated by Django 3.1.2 on 2020-10-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpllist', '0002_auto_20201004_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DetectModule',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
