# Generated by Django 3.1.2 on 2020-10-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpllist', '0004_customer_licensetable_sites_templates_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templates',
            options={'managed': False, 'verbose_name': 'tpl', 'verbose_name_plural': 'tpls'},
        ),
    ]
