# Generated by Django 3.1.2 on 2020-10-14 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpllist', '0006_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
