# Generated by Django 3.1.2 on 2020-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpllist', '0007_auto_20201014_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscript_date', models.IntegerField()),
                ('max_sites', models.IntegerField()),
            ],
            options={
                'db_table': 'license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=45, null=True)),
                ('site_url', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('server_env', models.CharField(blank=True, max_length=45, null=True)),
                ('framework', models.CharField(blank=True, max_length=45, null=True)),
                ('is_root', models.IntegerField()),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('tpl_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=45, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('permission', models.CharField(blank=True, max_length=45, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('tpl_path', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=45, null=True)),
                ('site_id', models.IntegerField(blank=True, null=True)),
                ('u_name', models.CharField(blank=True, max_length=45, null=True)),
                ('u_passwd', models.CharField(blank=True, max_length=45, null=True)),
                ('permission_lvl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LicenseTable',
        ),
        migrations.DeleteModel(
            name='Sites',
        ),
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
